apple_help: true  # Flag for conditional markup, if needed.
markdown: kramdown

# Localization collections for Help topics. Add more languages as needed.
collections:
  English.lproj:
    output: true

defaults:
  -
    scope:
      path: ""
    values:
      layout: "help-page"
      order: 0

exclude: ['Makefile', 'jekyll-server.command', 'Info.plist']
