name: Windfish

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cd lib; swift build -v
    - name: Run tests
      run: cd lib; swift test -v
